[font]
size = 19.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold   = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Thin Italic" }

[window]
dynamic_padding = true
opacity = 0.95

[window.dimensions]
columns = 93
lines = 25

[window.padding]
x = 10
y = 10

[colors]

[colors.primary]
background = "#2e3436"
foreground = "#d3d6c9"

[colors.cursor]
text = "#2e3436"
cursor = "#ffffff"

[colors.selection]
text = "#2e3436"
background = "#ffffff"

[colors.normal]
black = "#2e3436"
red = "#cd3e11"
green = "#8ae234"
yellow = "#fce94f"
blue = "#729fcf"
magenta = "#ad7fa8"
cyan = "#34e2e2"
white = "#d3d6c9"

[colors.bright]
black = "#555753"
red = "#ef2929"
green = "#9aff87"
yellow = "#f5f749"
blue = "#82afff"
magenta = "#f587ff"
cyan = "#8aeae2"
white = "#ffffff"

[cursor.style]
shape = "Beam"
blinking = "On"
